default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: spaceman
  username: spaceman
  password:
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

dev:
  <<: *default

demo:
  <<: *default