default: &default
  adapter: postgresql
  encoding: unicode
  encoding: SQL_ASCII
  host: localhost
  port: 5432
  database: spaceman
  username: spaceman
  password: spaceman
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

dev:
  <<: *default

demo:
  <<: *default  <<: *default
